### ISSUE TITLE
PDF Reporting

### ISSUE THREAD

**Issue by msaperst** [Coveros/selenified#52]
Currently, the detailed reports are HTML. They have dynamic information displayed, such as images that can be toggled. Could these HTML reports also be produced as PDFs, with imbedded images, and proper formatting, so that they could be easily uploaded/attached as supporting materials

**Comment by msaperst** [comment]
Instead, maybe just embed the image src in the html. so one file can still be used

**Comment by HammidFunsho** [comment]
@msaperst Just to confirm that the ticket scope has changed to embedding the image src into the HTML, rather than creating a PDF report?

**Comment by msaperst** [comment]
Closing this item after #121 is merged and completed
