### ISSUE TITLE
Update Setup Instructions

### ISSUE THREAD

**Issue by msaperst** [Coveros/selenified#57]
Include more detailed instructions for maven to include failsafe plugin, and testng setup

**Comment by HammidFunsho** [comment]
Wrote a blog post which details the setup for Maven and TestNG. Do we want to move some of those instructions to the README? @msaperst

**Comment by msaperst** [comment]
once it's published, and added to the wiki, i think that solves this

*[image: Max Saperstone]*


[image: Website] <https://www.coveros.com/> [image: LinkedIn]
<https://www.linkedin.com/in/maxsaperstone> [image: Twitter]
<https://twitter.com/Automate_Tests> [image: Email]
<max.saperstone@coveros.com>


*Mobile: *(571) 245-3351 <5712453351>

**Comment by HammidFunsho** [comment]
Blog post has been published, moving this to closed 
https://www.coveros.com/setting-selenified-using-maven/
